# Setup
title:            Simple IP Config
tagline:          'IP addresses'
description:      'description'
url:              https://kurtisliggett.github.io/Simple-IP-Config
baseurl:          https://kurtisliggett.github.io/Simple-IP-Config/

author:
  name:           'Kurtis Liggett'
  url:            https://kurtisliggett.github.io

paginate:         5

# Custom vars
version:          2.8

github:
  repo:           https://github.com/KurtisLiggett/Simple-IP-Config
