gems:
  - jekyll-seo-tag

# Setup
title:            Simple IP Config
tagline:          'IP addresses'
description:      'View and change your local IP addresses.'
url:              https://kurtisliggett.github.io/
baseurl:          Simple-IP-Config

author:
  name:           'Kurtis Liggett'
  url:            https://kurtisliggett.github.io

paginate:         5

# Custom vars
version:          2.8

github:
  repo:           https://github.com/KurtisLiggett/Simple-IP-Config
